mainapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .decorators import check_recaptcha
from . import views
from django.views.decorators.cache import cache_page
from django.contrib.auth import views
from django.conf.urls import url


from .views import (
    BaseView,
    ProductDetailView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    LoginView,
    RegistrationView, ProfileView,SearchResultsView,
    PayedOnlineOrderView
)


urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('login/', LoginView.as_view(), name='login'),
path('password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
path('password-reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
path('password-change/', views.PasswordChangeView.as_view(), name='password_change'),
path('password-change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('logout/', LogoutView.as_view(next_page="/"), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('search', SearchResultsView.as_view(), name='search_results'),
    path('payed-online-order/', PayedOnlineOrderView.as_view(), name='make_order'),

]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('product-specs/', include('specs.urls')),
    path('captcha/', include('captcha.urls'))
   
]
handler404 = 'mainapp.views.error_404_view'




if settings.DEBUG:
    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
import sys
from PIL import Image
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.utils import timezone
from io import BytesIO
from django.core.files.uploadedfile import  InMemoryUploadedFile
from cloudipsp import Api, Checkout


User = get_user_model()

class MinResolutionErrorEXception(Exception):
    pass

class MaxResolutionErrorEXception(Exception):
    pass


class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

class Product(models.Model):

    MIN_RESOLUTION = (100, 100)
    MAX_RESOLUTION =(250, 250)
    MAX_IMAGE_SIZE = 3145728

    #brand = models.CharField(max_length=255, verbose_name='Brand', default='default brand')
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
    features = models.ManyToManyField("specs.ProductFeatures", blank=True, related_name='features_for_product')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})

    def get_features(self):
        return {f.feature.feature_name: ' '.join([f.value, f.feature.unit or ""]) for f in self.features.all()}

    def save(self, *args, **kwargs):
     
           ## Обрезка изображения
           image = self.image
           img = Image.open(image)
           new_img = img.convert('RGB')
           resized_new_img = new_img.resize((250,250), Image.ANTIALIAS)
           ##new_img.thumbnail()
           filestream = BytesIO()
           resized_new_img.save(filestream, 'JPEG', quality=90)
           filestream.seek(0)
           name ='{}.'.format(self.image.name.split('.'))
           self.image = InMemoryUploadedFile(filestream, 'ImageField', name,'jpeg/image',
           sys.getsizeof(filestream), None)


           super().save(*args, **kwargs)


class CartProduct(models.Model):

    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    product = models.ForeignKey(Product, verbose_name='Товар', on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт: {} (для корзины)".format(self.product.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.product.price
        super().save(*args, **kwargs)


class Cart(models.Model):

    owner = models.ForeignKey('Customer', null=True, verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):

    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    orders = models.ManyToManyField('Order', blank=True, verbose_name='Заказы покупателя', related_name='related_order')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'
    STATUS_PAYED ='payed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_PAYED, 'Заказ оплачен'),
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен')
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель', related_name='related_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name='Статус заказ',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')
    order_date = models.DateField(verbose_name='Дата получения заказа', default=timezone.now)

    def __str__(self):
        return str(self.id)

mainapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Order
from captcha.fields import CaptchaField
import random

User = get_user_model()



class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = 'Дата получения заказа'

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment'
        )


class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)
    captcha = CaptchaField()
    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь с логином "{username} не найден в системе')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль")
        return self.cleaned_data


class RegistrationForm(forms.ModelForm):

    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    phone = forms.CharField(required=False)
    address = forms.CharField(required=False)
    email = forms.EmailField(required=True)
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['confirm_password'].label = 'Подтвердите пароль'
        self.fields['phone'].label = 'Номер телефона'
        self.fields['first_name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['address'].label = 'Адрес'
        self.fields['email'].label = 'Электронная почта'

    def clean_email(self):
        email = self.cleaned_data['email']
        domain = email.split('.')[-1]
        if domain in ['net']:
            raise forms.ValidationError(
                f'Регистрация для домена {domain} невозможна'
            )
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                f'Данный почтовый адрес уже зарегистрирован в системе'
            )
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(
                f'Имя {username} занято'
            )
        return username

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Пароли не совпадают')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'first_name', 'last_name','email']

mainapp/templates/1.html
{% load static %}
{% load search_filter %}
{% load cache %}
<!DOCTYPE html>
<html lang="ru">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Магазин</title>

<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">



 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

  <link href="{% static 'css/styles.css'%}" rel="stylesheet">

</head>
<body>



<header id="header" class="fixed-top">
<nav class="navbar navbar-expand-lg navbar-light " id="nav_foot">
  <div class="container">
    <a class="navbar-brand" id="a1" href="{% url 'base' %}"><img src="{% static 'icons/Tilda_Icons_3st_store.svg' %}" width="28" height="28"></a>
    <div class="container">
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active " id="a1" aria-current="page" href="{% url 'login' %}">Авторизация</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" id="a1" href="{% url 'registration' %}">Регистрация</a>
          
        </li>
      
               {% else %}
        <li class="nav-item">
                  {% if request.user.is_authenticated %}<span class="badge rounded-pill  text-dark " id="bg2" style="background-color:darkseagreen;"><a href="{% url 'profile' %}" id="a1" style="text-decoration: none; font-size: 14px;"><img src="{% static 'icons/Tilda_Icons_3st_man.svg' %}" width="28" height="28 ">{{ request.user.username }}</a></span>
                  <span class="navbar-text text-dark">{% else %} гоcть!{% endif %}
                <a href="{% url 'logout' %}" id="a1" style="text-decoration: none; font-size: 14px;">Выйти</a>
                  
              </li>
          {% endif %}
          </ul>
          <ul class="navbar-nav ml-auto">
          <li class="nav-item">
         
        
            <a class="nav-link" id="a1" style="text-decoration: none; font-size: 16px;" href="{% url 'cart' %}" ><img  src="{% static 'icons/Tilda_Icons_3st_cart.svg' %}" width="29" height="29" style="display: inline-block">
            <span class="badge bg-primary text-dark" id="bg1" >{{ cart.products.count }}</span></a>
          </li>
        </ul>
    </div>
</div>
  </div>
</nav>

</header>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3 mt-5">
        <div class="list-group">
          {% for category in categories %}
          <a href="{{ category.get_absolute_url }}" id="a1" class="list-group-item">{{ category.name }} ({{ category.product_set.count }})</a>
          {% endfor %}
        </div>

   
      {% block productfilter %}

       <form class="d-flex mt-3"  action="/search"  method="GET">   {% csrf_token %}
        <input class="form-control me-2" name="search" type="search" placeholder="Поиск товара" aria-label="Search">
        <button class="btn rounded-pill  text-dark  btn-outline-primary "  type="submit">Поиск</button>
      </form>
       
      {% endblock productfilter %}
      </div>
      
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">
        {% block content %}
        {% if messages %}
            {% for message in messages %}
              <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close"  id="btn1" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true"></span>
                </button>
              </div>
            {% endfor %}
        {% endif %}
        

  {% cache 500 sidebar %}
     <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/for_carousel/img_5090_3_1.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/for_carousel/2.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/for_carousel/3.jpg' %}" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

  {% endcache %}




        <div class="row mt-5">
 
          {% for product in products %}
  
          
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <h5 class="price">{{ product.price }} руб.</h5>
                <a href="{% url 'add_to_cart' slug=product.slug %}">
                  <button class="btn rounded-pill text-dark  btn-danger btn-sm">Добавить в корзину</button>
                </a>
              </div>
            </div>
            
          </div>
           
          {% endfor %}
    

        </div>
        
      
      {% endblock content %}
      
    <!--Pagination-->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% if products.has_previous %}
            <li class="page-item">
            <a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
          </li>
        {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
          </li>
        {% endif %}

        {% if products.number|add:'-4' > 1 %}
            <li class="page-item"><a class="page-link" href="?page={{ products.number|add:'-5' }}">&hellip;</a></li>
        {% endif %}

        {% for i in products.paginator.page_range %}
            {% if products.number == i %}
                <li class="page-item active" aria-current="page">
              <span class="page-link">
                {{ i }}
                <span class="sr-only">(current)</span>
              </span>
            </li>
            {% elif i > products.number|add:'-5' and i < products.number|add:'5' %}
                 <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if products.paginator.num_pages > products.number|add:'4' %}
           <li class="page-item"><a class="page-link" href="?page={{ products.number|add:'5' }}">&hellip;</a></li>
        {% endif %}

        {% if products.has_next %}
            <li class="page-item">
            <a class="page-link" href="?page={{ products.next_page_number }}">Next</a>
          </li>
        {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
          </li>
        {% endif %}
      </ul>
    </nav>
    <!--end of Pagination-->

    <!--end of Pagination-->
      
      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>


 <!-- Footer -->
<footer class="text-center text-lg-start" id="nav_foot">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 span class="text-uppercase">О нас</h5>
          <img src="{% static 'icons/Tilda_Icons_1ed_location.svg' %}"  width="30" height="30">Туркестан, ул.ТаукеХана 200</img>
          <hr>
          <img src="{% static 'icons/Tilda_Icons_3st_round-the-clock.svg' %}" width="30" height="30">График работы: Круглосуточно</img>
           <hr>
        <img src="{% static 'icons/Tilda_Icons_3st_van.svg' %}" width="30" height="30">Бесплатная доставка </img>
        </p>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase"></h5>

        <ul class="list-unstyled mb-0">
          <li>
            <a href="#!" class="text-dark"></a>
          </li>
          <li>
            <a href="#!" class="text-dark"></a>
          </li>
          <li>
            <a href="#!" class="text-dark"></a>
          </li>
          <li>
            <a href="#!" class="text-dark"></a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase mb-0">Свяжитесь с нами</h5>

        <ul class="list-unstyled">
         </li>
            <li style="padding:5px;">
          <span><img src="{% static 'icons/Tilda_Icons_42_restaurant_phone.svg' %}" id="a1"  width="37" height="37">+7XXXXXXX</img></span>
          </li>
          <li style="padding:5px;">
           <a href="#" class="text-dark" >
          <img src="{% static 'icons/icons8-telegram-app.svg' %}" id="a1" width="33" height="33"></a>
          </li>
          <li style="padding:5px;">
            <a href="#!" class="text-dark">
          <img src="{% static 'icons/Tilda_Icons_26snw_instagram.svg' %}" id="a1" width="30" height="30"></a>
          </li>
          <li style="padding:5px;">
            <a href="mailto:mussayevr007@gmail.com" class="text-dark">
          <img src="{% static 'icons/envelope.svg' %}" id="a1"  width="30" height="30"></a>
         
        </ul>
      </div>
      
      
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <a class="text-dark" href="#">Ramazan Mussayev</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
<script src="{%static 'js/main.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
</body>

</html>

mainapp/templates/filter_other.html
       <form class="d-flex mt-3"  action="/search"  method="GET">   {% csrf_token %}
        <input class="form-control me-2" name="search" type="search" placeholder="Поиск товара" aria-label="Search">
        <button class="btn rounded-pill  text-dark  btn-outline-primary "  type="submit">Поиск</button>
      </form>
       

mainapp/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<link href="{% static 'css/styles.css'%}" rel="stylesheet">
<h3 class="mt-3 mb-3" style="text-align:center; padding-top: 40px;" >Ваши заказы {{ request.user.name }}</h3>
{% if not orders.count %}
<div class="col-md-12" style="margin-top:300px; margin-bottom:300px;">
  <h3>У вас еще нет заказов. <a href="{% url 'base' %}">Начните делать покупки!</a></h3>
</div>
{% else %}
<div class="col-md-12" style="margin-top:250px; margin-bottom:250px;">
  <table class="table">
    <thead>
      <th scope="col">Номер</th>
      <th scope="col">Cтатус</th>
      <th scope="col">Сумма</th>
      <th scope="col">Товар</th>
      <th scope="col">Дополнительно</th>

    </thead>
    <tbody>
    {% for order in orders %}
      <tr>
        <th scope="row">{{ order.id}}</th>
        <td>{{order.get_status_display}}</td>
        <td>{{order.cart.final_price}} руб.</td>
         <td>
           <ul>
           {% for item in order.cart.products.all %}

           <li>{{ item.product.title }} x {{ item.qty}}</li>

           {% endfor %}

           </ul>
          </td>
         <td>
           <button class="btn rounded-pill  btn-primary" data-bs-toggle="modal"  id="btn1" data-bs-target="#exampleModal-{{ order.id }}" >Дополнительно</button>
           <div class="modal fade" id="exampleModal-{{ order.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title " id="exampleModalLabel">Детализация заказа</h5>
        <button type="button"  id="btn1" class="btn-close rounded-pill" data-bs-dismiss="modal" aria-label="Close"></button>
        </button>
      </div>
      <div class="modal-body">
        <h3 class="text-center">Товар</h3>
       <table class="table">
         <thead>
           <tr>
             <th scope="col">Наименование</th>
             <th scope="col">Изображение</th>
             <th scope="col">Цена</th>
             <th scope="col">Кол-во</th>
             <th scope="col">Общая цена</th>
           </tr>
         </thead>
         <tbody>
           {% for item in order.cart.products.all %}
           <tr>
             <th scope="row">{{ item.product.title }}</th>
             <td class="w-25"><img src="{{ item.product.image.url }}" class="img-fluid" alt=""></td>
             <td><strong>{{ item.product.price}}</strong></td>
             <td>{{item.qty}}</td>
             <td>{{ item.final_price }} руб.</td>
           </tr>
           {% endfor %}
           <tr>
             <td colspan="2"></td>
             <td>Итого:</td>
             <td>{{ order.cart.total_products}}</td>
             <td><strong>{{order.cart.final_price}}</strong> руб.</td>
           </tr>
         </tbody>
       </table>
       <hr>
       <h4 class="text-center">Дополнительная информация</h4>
       <p>Имя: <strong>{{ order.first_name }}</strong></p>
       <p>Фамилия: <strong>{{ order.last_name }}</strong></p>
       <p>Телефон: <strong>{{ order.phone }}</strong></p>
       <p>Адресс: <strong>{{ order.address }}</strong></p>
      </div>
      <div class="modal-footer">
        <button type="button"  id="btn1" class="btn rounded-pill btn-danger" data-bs-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>
         </td>
        </tr>

    {% endfor %}
    </tbody>
  </table>
</div>

{% endif %}

{% endblock content%}